- hosts: localhost
  vars:
    user_home: "{{ lookup('env', 'HOME') }}"
    user_name: "{{ lookup('env', 'USER') }}"
    source_key: "{{ ansible_env.PWD }}/.ssh/id_rsa"
    dest_key: "{{ user_home }}/.ssh/id_rsa"
  pre_tasks:
    - name: Update apt cache
      become: true
      apt:
        update_cache: yes
      tags: zsh
      when: ansible_facts['os_family'] == 'Debian'

    - name: Update Homebrew
      homebrew:
        update_homebrew: yes
      tags: brew
      become: false
      when: ansible_facts['os_family'] == 'Darwin'

  tasks:
    - include_tasks: tasks/setup-config-dir.yml
      tags:
        - config

    - include_tasks: tasks/ssh.yml
      tags:
        - ssh

    - include_tasks: tasks/core-tools.yml
      tags:
        - install

    - include_tasks: tasks/neovim.yml
      tags:
        - nvim

    - include_tasks: tasks/macos.yml
      tags:
        - macos

    - include_tasks: tasks/zsh.yml
      tags:
        - zsh

    - include_tasks: tasks/node.yml
      tags:
        - node

    - include_tasks: tasks/java.yml
      tags:
        - java

    - include_tasks: tasks/dotfiles.yml
      tags:
        - dotfiles

    - include_tasks: tasks/tmux-plugins.yml
      tags:
        - tmux-plugins

    - include_tasks: tasks/iterm2.yml
      tags:
        - iterm2

    - include_tasks: tasks/dotfiles-update.yml
      tags:
        - dotfiles-update
