# Quick update playbook for existing machines
- hosts: localhost
  vars:
    user_home: "{{ lookup('env', 'HOME') }}"

  tasks:
    - name: Pull latest ansible playbooks
      command: git pull
      args:
        chdir: "{{ lookup('env', 'HOME') }}/me/ansible"
      ignore_errors: true
      tags: always

    - name: Pull latest dotfiles
      include_tasks: tasks/dotfiles-update.yml
      tags: dotfiles

    - name: Ensure Starship is installed (macOS)
      homebrew:
        name: starship
        state: present
      become: false
      when: ansible_facts['system'] == 'Darwin'
      tags: zsh

    - name: Ensure Starship is installed (Linux)
      become: true
      apt:
        name: starship
        state: present
      when: ansible_facts['system'] != 'Darwin'
      tags: zsh

    - name: Update tmux plugins
      include_tasks: tasks/tmux-plugins.yml
      tags: tmux

    - name: Sync Neovim plugins (PackerSync)
      shell: nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
      tags: nvim

    - name: Sync iTerm2 configuration
      include_tasks: tasks/iterm2.yml
      tags: iterm2
