- name: Ensure Homebrew is installed
  homebrew:
    state: present
  tags:
    - core
    - install

- name: Install Core Development Tools
  homebrew:
    name:
      - git
      - zsh
      - ripgrep
      - tmux
      - neovim
      - awscli
      - jq
    state: present
  tags:
    - core
    - install

- name: Install Browsers
  homebrew:
    name:
      - firefox
      - google-chrome
      - brave-browser
    state: present
  tags:
    - core
    - browser

- name: Install Productivity Applications
  homebrew:
    name:
      - alfred
      - iterm2
      - notion
      - slack
    state: present
  tags:
    - core
    - productivity

- name: Install Docker
  homebrew:
    name: docker
    state: present
  tags:
    - core
    - install

- name: Install Oh My Zsh
  shell: |
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: /Users/{{ ansible_user }}/.oh-my-zsh
  tags:
    - core
    - install

- name: Set Key Repeat Rate
  command: defaults write -g KeyRepeat -int 2
  tags:
    - core
    - config

- name: Set Initial Key Repeat Rate
  command: defaults write -g InitialKeyRepeat -int 11
  tags:
    - core
    - config
