- name: Update apt cache
  apt:
    update_cache: yes
  tags:
    - core
    - install
  become: true
  when: ansible_facts['system'] != 'Darwin'

- name: Update Homebrew
  homebrew:
    update_homebrew: yes
  tags:
    - core
    - install
  become: false
  when: ansible_facts['system'] == 'Darwin'

- name: Install Core Development Tools (Linux)
  apt:
    name:
      - git
      - zsh
      - ripgrep
      - tmux
      - awscli
      - jq
      - fzf
    state: present
  tags:
    - core
    - install
  become: true
  when: ansible_facts['system'] != 'Darwin'

- name: Install Core Development Tools (macOS)
  homebrew:
    name:
      - git
      - zsh
      - ripgrep
      - tmux
      - awscli
      - fzf
      - jq
    state: present
  tags:
    - core
    - install
  become: false
  when: ansible_facts['system'] == 'Darwin'

- name: Check if Firefox is installed (macOS)
  stat:
    path: /Applications/Firefox.app
  register: firefox_installed
  when: ansible_facts['system'] == 'Darwin'
  tags:
    - core
    - browser

- name: Install Firefox (macOS)
  homebrew_cask:
    name: firefox
    state: present
  become: false
  when:
    - ansible_facts['system'] == 'Darwin'
    - not firefox_installed.stat.exists
  tags:
    - core
    - browser

- name: Check if Chromium is installed (macOS)
  stat:
    path: /Applications/Chromium.app
  register: chromium_installed
  when: ansible_facts['system'] == 'Darwin'
  tags:
    - core
    - browser

- name: Install Chromium (macOS)
  homebrew_cask:
    name: chromium
    state: present
  become: false
  when:
    - ansible_facts['system'] == 'Darwin'
    - not chromium_installed.stat.exists
  tags:
    - core
    - browser

- name: Check if Brave Browser is installed (macOS)
  stat:
    path: "/Applications/Brave Browser.app"
  register: brave_installed
  when: ansible_facts['system'] == 'Darwin'
  tags:
    - core
    - browser

- name: Install Brave Browser (macOS)
  homebrew_cask:
    name: brave-browser
    state: present
  become: false
  when:
    - ansible_facts['system'] == 'Darwin'
    - not brave_installed.stat.exists
  tags:
    - core
    - browser

- name: Install Browsers (Linux)
  apt:
    name:
      - firefox
      - chromium-browser
    state: present
  tags:
    - core
    - browser
  become: true
  when: ansible_facts['system'] != 'Darwin'

- name: Check if Notion is installed (macOS)
  stat:
    path: /Applications/Notion.app
  register: notion_installed
  when: ansible_facts['system'] == 'Darwin'
  tags:
    - productivity

- name: Install Notion (macOS)
  homebrew_cask:
    name: notion
    state: present
  become: false
  when:
    - ansible_facts['system'] == 'Darwin'
    - not notion_installed.stat.exists
  tags:
    - productivity

- name: Alfred
  homebrew_cask:
    name: alfred
    state: present
  become: false
  when: ansible_facts['system'] == 'Darwin'
  tags:
    - install
    - productivity

- name: Install iTerm2 (macOS)
  homebrew_cask:
    name: iterm2
    state: present
  become: false
  when: ansible_facts['system'] == 'Darwin'
  tags:
    - terminal

- name: Install missing packages (Linux)
  shell: apt-get install -y --fix-missing
  tags:
    - core
    - install
  become: true
  when: ansible_facts['system'] != 'Darwin'
