- name: Update apt cache
  apt:
    update_cache: yes
  tags:
    - core
    - install

- name: Install Core Development Tools
  apt:
    name:
      - git
      - zsh
      - ripgrep
      - tmux
      - awscli
      - jq
    state: present
  tags:
    - core
    - install

- name: Install Browsers
  apt:
    name:
      - firefox
      - chromium-browser
    state: present
  tags:
    - core
    - browser

- name: Install missing packages
  shell: apt-get install -y --fix-missing
  tags:
    - core
    - install