- name: Set macOS keyboard settings
  connection: local
  osx_defaults:
    domain: NSGlobalDomain
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    type: int
  loop:
    - { key: KeyRepeat, value: 2 }
    - { key: InitialKeyRepeat, value: 11 }
  when: ansible_facts['system'] == 'Darwin'
  tags:
    - macos
    - keyboard

- name: Disable press-and-hold for keys in favor of key repeat
  osx_defaults:
    domain: NSGlobalDomain
    key: ApplePressAndHoldEnabled
    type: bool
    value: false
  when: ansible_facts['system'] == 'Darwin'
  tags:
    - macos
    - keyboard

- name: Set macOS to use ISO 8601 date format via en_DK locale
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleLocale
    value: "en_DK"
  tags:
    - macos
    - locale
