- name: Update apt cache
  apt:
    update_cache: yes
  tags:
    - nvim
    - install

- name: Install Neovim and essential packages
  apt:
    name:
      - neovim
      - git
      - curl
      - unzip
      - build-essential
    state: present
  tags:
    - nvim
    - install

