- name: Remove old Neovim package if installed (Linux)
  become: true
  ansible.builtin.apt:
    name: neovim
    state: absent
  tags:
    - nvim
  when: ansible_facts['system'] != 'Darwin'

- name: Remove old Neovim package if installed (macOS)
  become: false
  ansible.builtin.homebrew:
    name: neovim
    state: absent
  tags:
    - nvim
  when: ansible_facts['system'] == 'Darwin'

- name: Add Neovim PPA (Linux)
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:neovim-ppa/stable
    state: present
    update_cache: yes
  tags:
    - nvim
  when: ansible_facts['system'] != 'Darwin'

- name: Install Neovim (v0.5+) (Linux)
  become: true
  ansible.builtin.apt:
    name: neovim
    state: present
    update_cache: yes
  tags:
    - nvim
  when: ansible_facts['system'] != 'Darwin'

- name: Install Neovim (v0.5+) (macOS)
  become: false
  ansible.builtin.homebrew:
    name: neovim
    state: present
  tags:
    - nvim
  when: ansible_facts['system'] == 'Darwin'

- name: Ensure packer.nvim is installed
  git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    depth: 1
    update: no
  tags:
    - nvim
    - packer
