- name: Remove old Neovim package if installed
  become: true
  ansible.builtin.apt:
    name: neovim
    state: absent
  tags:
    - nvim

- name: Add Neovim PPA
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:neovim-ppa/stable
    state: present
    update_cache: yes
  tags:
    - nvim

- name: Install Neovim (v0.5+)
  become: true
  ansible.builtin.apt:
    name: neovim
    state: present
    update_cache: yes
  tags:
    - nvim

- name: Ensure Packer directory exists
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start"
    state: directory
    mode: '0755'
  tags:
    - nvim

- name: Get Packer
  ansible.builtin.git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    version: master
  tags:
    - nvim

- name: Run PackerSync
  ansible.builtin.shell: |
    nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
  tags:
    - nvim