- name: Install NVM and Node.js
  hosts: localhost
  tasks:
    - block:
        - name: Download NVM install script
          get_url:
            url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh
            dest: /tmp/install_nvm.sh
            mode: '0755'
          tags:
            - node
            - install

        - name: Run NVM install script
          shell: /tmp/install_nvm.sh
          args:
            creates: ~/.nvm
          tags:
            - node
            - install

        - name: Ensure NVM is loaded in .zshrc
          lineinfile:
            path: ~/.zshrc
            line: |
              export NVM_DIR="$HOME/.nvm"
              [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          tags:
            - node
            - setup

        - name: Source NVM in the current session
          shell: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          tags:
            - node
            - setup

        - name: Install Node.js v20.3.0 using NVM
          shell: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 20.3.0
          tags:
            - node
            - install
      when: ansible_facts['os_family'] == 'Darwin' or ansible_facts['os_family'] == 'Debian'