- name: Ensure .ssh directory exists
  file:
    path: "{{ dest_key | dirname }}"
    mode: '0700'
    state: directory
  tags:
    - ssh
  become: false

- name: Install SSH private key
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: '0600'
  tags:
    - ssh
  become: false

- name: Install SSH public key
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: '0644'
  tags:
    - ssh
  become: false

- name: Add SSH private key to the agent
  shell: |
    eval "$(ssh-agent -s)"
    ssh-add "{{ dest_key }}"
  tags:
    - ssh
  become: false

- name: Set authorized key from file
  authorized_key:
    user: "{{ user_name }}"
    state: present
    key: "{{ lookup('file', source_key + '.pub') }}"
  tags:
    - ssh
  become: false